const { createStoreRankEmbed } = require('../utils/combat');
const logger = require('../utils/logger');

/**
 * Massive Combat System Expansion
 * Creates 100+ enemies per rank with proper CP scaling
 */

const massiveCombatExpansion = {
    // Normal Rank Enemies (100+ enemies, CP: 50-150)
    normal: [
        // Pure Titans (30 variants)
        { name: 'Mindless Pure Titan', power: 75, type: 'titan', description: 'Basic mindless titan driven by hunger' },
        { name: 'Wandering Pure Titan', power: 70, type: 'titan', description: 'Aimlessly roaming titan' },
        { name: 'Aggressive Pure Titan', power: 85, type: 'titan', description: 'Unusually hostile pure titan' },
        { name: 'Small Pure Titan', power: 60, type: 'titan', description: '3-meter class pure titan' },
        { name: 'Medium Pure Titan', power: 80, type: 'titan', description: '7-meter class pure titan' },
        { name: 'Large Pure Titan', power: 95, type: 'titan', description: '12-meter class pure titan' },
        { name: 'Crawler Titan', power: 65, type: 'titan', description: 'Titan that moves on all fours' },
        { name: 'Jumping Titan', power: 88, type: 'titan', description: 'Titan with enhanced leaping ability' },
        { name: 'Running Titan', power: 92, type: 'titan', description: 'Unusually fast pure titan' },
        { name: 'Climbing Titan', power: 78, type: 'titan', description: 'Titan that scales walls efficiently' },
        { name: 'Screaming Titan', power: 72, type: 'titan', description: 'Titan with piercing vocal cords' },
        { name: 'Grabbing Titan', power: 83, type: 'titan', description: 'Titan with oversized hands' },
        { name: 'Biting Titan', power: 87, type: 'titan', description: 'Titan with massive jaw strength' },
        { name: 'Stalking Titan', power: 74, type: 'titan', description: 'Titan that follows silently' },
        { name: 'Pack Titan', power: 79, type: 'titan', description: 'Titan that hunts in groups' },
        { name: 'Night Titan', power: 81, type: 'titan', description: 'Titan active during darkness' },
        { name: 'Underground Titan', power: 68, type: 'titan', description: 'Titan found in caves' },
        { name: 'Forest Titan', power: 76, type: 'titan', description: 'Titan adapted to woodland' },
        { name: 'Wall Titan Remnant', power: 89, type: 'titan', description: 'Fragment of wall titan' },
        { name: 'Hungry Titan', power: 84, type: 'titan', description: 'Exceptionally ravenous titan' },
        { name: 'Lost Titan', power: 71, type: 'titan', description: 'Confused wandering titan' },
        { name: 'Injured Titan', power: 63, type: 'titan', description: 'Titan with battle scars' },
        { name: 'Ancient Titan', power: 93, type: 'titan', description: 'Very old pure titan' },
        { name: 'Fresh Titan', power: 67, type: 'titan', description: 'Recently transformed human' },
        { name: 'Berserker Titan', power: 96, type: 'titan', description: 'Frenzied pure titan' },
        { name: 'Sleepy Titan', power: 58, type: 'titan', description: 'Sluggish slow-moving titan' },
        { name: 'Alert Titan', power: 86, type: 'titan', description: 'Highly aware pure titan' },
        { name: 'Territorial Titan', power: 82, type: 'titan', description: 'Titan guarding specific area' },
        { name: 'Mimic Titan', power: 77, type: 'titan', description: 'Titan that copies behavior' },
        { name: 'Titan Spawn', power: 59, type: 'titan', description: 'Newly emerged titan' },

        // Military Personnel (35 variants)
        { name: 'Garrison Recruit', power: 52, type: 'human', description: 'New wall defense trainee' },
        { name: 'Garrison Soldier', power: 58, type: 'human', description: 'Standard wall defender' },
        { name: 'Garrison Veteran', power: 67, type: 'human', description: 'Experienced wall guard' },
        { name: 'Garrison Captain', power: 75, type: 'human', description: 'Wall defense unit leader' },
        { name: 'Military Police Cadet', power: 55, type: 'human', description: 'Interior police trainee' },
        { name: 'Military Police Officer', power: 62, type: 'human', description: 'Interior law enforcement' },
        { name: 'Military Police Sergeant', power: 70, type: 'human', description: 'Mid-rank police officer' },
        { name: 'Military Police Commander', power: 78, type: 'human', description: 'High-rank police leader' },
        { name: 'Scout Cadet', power: 53, type: 'human', description: 'Survey Corps trainee' },
        { name: 'Scout Soldier', power: 60, type: 'human', description: 'Standard survey member' },
        { name: 'Scout Veteran', power: 69, type: 'human', description: 'Experienced explorer' },
        { name: 'Scout Squad Leader', power: 76, type: 'human', description: 'Survey team commander' },
        { name: 'Marley Recruit', power: 54, type: 'human', description: 'Marleyan army trainee' },
        { name: 'Marley Soldier', power: 61, type: 'human', description: 'Standard Marleyan fighter' },
        { name: 'Marley Sergeant', power: 68, type: 'human', description: 'Marleyan squad leader' },
        { name: 'Marley Officer', power: 74, type: 'human', description: 'Marleyan military officer' },
        { name: 'Training Corps Instructor', power: 65, type: 'human', description: 'Military trainer' },
        { name: 'Artillery Specialist', power: 63, type: 'human', description: 'Cannon operation expert' },
        { name: 'Supply Sergeant', power: 56, type: 'human', description: 'Logistics coordinator' },
        { name: 'Wall Engineer', power: 59, type: 'human', description: 'Fortification specialist' },
        { name: 'Medical Corps', power: 51, type: 'human', description: 'Military field medic' },
        { name: 'Signal Corps', power: 57, type: 'human', description: 'Communication specialist' },
        { name: 'Stable Master', power: 49, type: 'human', description: 'Horse care specialist' },
        { name: 'Weapon Smith', power: 64, type: 'human', description: 'Military equipment maker' },
        { name: 'Guard Captain', power: 72, type: 'human', description: 'Security detail leader' },
        { name: 'Night Watchman', power: 48, type: 'human', description: 'Overnight security guard' },
        { name: 'Gate Guard', power: 58, type: 'human', description: 'Entry point defender' },
        { name: 'Patrol Leader', power: 66, type: 'human', description: 'Reconnaissance patrol head' },
        { name: 'Drill Sergeant', power: 71, type: 'human', description: 'Training specialist' },
        { name: 'Military Judge', power: 73, type: 'human', description: 'Military court officer' },
        { name: 'Intelligence Officer', power: 69, type: 'human', description: 'Information gathering specialist' },
        { name: 'Tactical Advisor', power: 77, type: 'human', description: 'Strategic planning expert' },
        { name: 'Combat Engineer', power: 65, type: 'human', description: 'Battle construction specialist' },
        { name: 'Quartermaster', power: 54, type: 'human', description: 'Supply distribution manager' },
        { name: 'Military Chaplain', power: 46, type: 'human', description: 'Spiritual guidance provider' },

        // Civilians and Others (35+ variants)
        { name: 'Terrified Civilian', power: 35, type: 'human', description: 'Panicked citizen' },
        { name: 'Armed Merchant', power: 47, type: 'human', description: 'Trader with weapons' },
        { name: 'Bandit Scout', power: 52, type: 'human', description: 'Outlaw advance guard' },
        { name: 'Bandit Raider', power: 59, type: 'human', description: 'Criminal gang member' },
        { name: 'Bandit Leader', power: 68, type: 'human', description: 'Outlaw gang chief' },
        { name: 'Underground Thug', power: 55, type: 'human', description: 'Criminal from below' },
        { name: 'Underground Boss', power: 73, type: 'human', description: 'Crime syndicate leader' },
        { name: 'Wall Cultist', power: 44, type: 'human', description: 'Wall worship fanatic' },
        { name: 'Cult Enforcer', power: 61, type: 'human', description: 'Religious militant' },
        { name: 'Cult High Priest', power: 79, type: 'human', description: 'Cult spiritual leader' },
        { name: 'Titan Researcher', power: 50, type: 'human', description: 'Scientific investigator' },
        { name: 'Mad Scientist', power: 64, type: 'human', description: 'Unethical experimenter' },
        { name: 'Refugee Fighter', power: 43, type: 'human', description: 'Displaced person with weapons' },
        { name: 'Merchant Guard', power: 56, type: 'human', description: 'Caravan protector' },
        { name: 'Caravan Leader', power: 62, type: 'human', description: 'Trade expedition head' },
        { name: 'Blackmarket Dealer', power: 48, type: 'human', description: 'Illegal goods trader' },
        { name: 'Information Broker', power: 53, type: 'human', description: 'Secret knowledge seller' },
        { name: 'Propaganda Spreader', power: 41, type: 'human', description: 'Political agitator' },
        { name: 'Eldian Sympathizer', power: 45, type: 'human', description: 'Pro-Eldian activist' },
        { name: 'Marley Citizen', power: 38, type: 'human', description: 'Hostile civilian' },
        { name: 'Paradis Islander', power: 40, type: 'human', description: 'Island native fighter' },
        { name: 'Farm Defender', power: 49, type: 'human', description: 'Agricultural area guard' },
        { name: 'Village Militia', power: 54, type: 'human', description: 'Local defense force' },
        { name: 'Tavern Brawler', power: 51, type: 'human', description: 'Bar fight specialist' },
        { name: 'Street Fighter', power: 57, type: 'human', description: 'Urban combat veteran' },
        { name: 'Scavenger Leader', power: 46, type: 'human', description: 'Resource gathering chief' },
        { name: 'Wasteland Nomad', power: 42, type: 'human', description: 'Desert wanderer' },
        { name: 'Forest Ranger', power: 58, type: 'human', description: 'Woodland protector' },
        { name: 'Mountain Climber', power: 52, type: 'human', description: 'High altitude specialist' },
        { name: 'Cave Explorer', power: 47, type: 'human', description: 'Underground navigator' },
        { name: 'Ruins Guardian', power: 66, type: 'human', description: 'Ancient site protector' },
        { name: 'Artifact Hunter', power: 60, type: 'human', description: 'Treasure seeker' },
        { name: 'Lost Soldier', power: 63, type: 'human', description: 'Stranded military personnel' },
        { name: 'Deserter', power: 57, type: 'human', description: 'Military runaway' },
        { name: 'Hermit Warrior', power: 71, type: 'human', description: 'Isolated combat expert' },
        { name: 'Beast Tamer', power: 65, type: 'human', description: 'Animal control specialist' },
        { name: 'Trap Specialist', power: 59, type: 'human', description: 'Mechanical trap expert' },
        { name: 'Poison Master', power: 55, type: 'human', description: 'Toxin warfare specialist' },
        { name: 'Fire Wielder', power: 69, type: 'human', description: 'Flame weapon expert' },
        { name: 'Ice Fighter', power: 61, type: 'human', description: 'Cold climate warrior' }
    ],

    // Rare Rank Enemies (100+ enemies, CP: 200-400)
    rare: [
        // Advanced Titans (40 variants)
        { name: 'Abnormal Titan Alpha', power: 250, type: 'titan', description: 'Highly intelligent abnormal titan' },
        { name: 'Deviant Titan Prime', power: 280, type: 'titan', description: 'Unpredictable behavior titan' },
        { name: 'Berserker Titan Elite', power: 320, type: 'titan', description: 'Frenzied combat titan' },
        { name: 'Stalker Titan Advanced', power: 240, type: 'titan', description: 'Silent hunting titan' },
        { name: 'Climber Titan Master', power: 260, type: 'titan', description: 'Wall scaling specialist' },
        { name: 'Runner Titan Swift', power: 290, type: 'titan', description: 'Extremely fast titan' },
        { name: 'Jumper Titan High', power: 270, type: 'titan', description: 'Enhanced leaping titan' },
        { name: 'Grabber Titan Strong', power: 300, type: 'titan', description: 'Powerful grasping titan' },
        { name: 'Biter Titan Fierce', power: 310, type: 'titan', description: 'Devastating bite titan' },
        { name: 'Screamer Titan Loud', power: 230, type: 'titan', description: 'Sonic attack titan' },
        { name: 'Pack Leader Titan', power: 340, type: 'titan', description: 'Commands other titans' },
        { name: 'Night Hunter Titan', power: 275, type: 'titan', description: 'Darkness specialist titan' },
        { name: 'Forest Predator Titan', power: 285, type: 'titan', description: 'Woodland ambush titan' },
        { name: 'Cave Dweller Titan', power: 255, type: 'titan', description: 'Underground adapted titan' },
        { name: 'Territorial Alpha Titan', power: 330, type: 'titan', description: 'Area controlling titan' },
        { name: 'Mimic Master Titan', power: 295, type: 'titan', description: 'Advanced copying titan' },
        { name: 'Titan Serum Subject', power: 315, type: 'titan', description: 'Experimental enhancement' },
        { name: 'Hybrid Transformation', power: 350, type: 'titan', description: 'Partial shifter titan' },
        { name: 'Wall Breach Titan', power: 320, type: 'titan', description: 'Wall destruction specialist' },
        { name: 'Memory Fragment Titan', power: 280, type: 'titan', description: 'Retains human memories' },
        { name: 'Coordinate Echo Titan', power: 360, type: 'titan', description: 'Founding power remnant' },
        { name: 'Paths Touched Titan', power: 370, type: 'titan', description: 'Paths dimension affected' },
        { name: 'Royal Blood Titan', power: 380, type: 'titan', description: 'Fritz bloodline titan' },
        { name: 'Ackerman Titan', power: 390, type: 'titan', description: 'Ackerman transformed' },
        { name: 'Warrior Candidate Titan', power: 340, type: 'titan', description: 'Marley trainee titan' },
        { name: 'Eldian Restorationist Titan', power: 310, type: 'titan', description: 'Rebellion member titan' },
        { name: 'Spy Network Titan', power: 290, type: 'titan', description: 'Intelligence operation titan' },
        { name: 'Underground King Titan', power: 350, type: 'titan', description: 'Crime boss titan' },
        { name: 'Cult Leader Titan', power: 325, type: 'titan', description: 'Religious fanatic titan' },
        { name: 'Merchant Prince Titan', power: 300, type: 'titan', description: 'Wealthy trader titan' },
        { name: 'Military Scientist Titan', power: 335, type: 'titan', description: 'Research specialist titan' },
        { name: 'Propaganda Minister Titan', power: 285, type: 'titan', description: 'Information warfare titan' },
        { name: 'Weapon Master Titan', power: 345, type: 'titan', description: 'Combat expert titan' },
        { name: 'Tactical Genius Titan', power: 355, type: 'titan', description: 'Strategic planning titan' },
        { name: 'Survival Expert Titan', power: 315, type: 'titan', description: 'Wilderness specialist titan' },
        { name: 'Stealth Master Titan', power: 325, type: 'titan', description: 'Infiltration expert titan' },
        { name: 'Demolition Titan', power: 365, type: 'titan', description: 'Explosive specialist titan' },
        { name: 'Engineer Titan', power: 295, type: 'titan', description: 'Construction expert titan' },
        { name: 'Medic Titan', power: 275, type: 'titan', description: 'Healing specialist titan' },
        { name: 'Communication Titan', power: 265, type: 'titan', description: 'Signal specialist titan' },

        // Elite Human Forces (60+ variants)
        { name: 'Marley Warrior Candidate', power: 320, type: 'human', description: 'Elite titan inheritance candidate' },
        { name: 'Ackerman Descendant', power: 380, type: 'human', description: 'Awakened superhuman bloodline' },
        { name: 'Royal Guard Elite', power: 350, type: 'human', description: 'Fritz family protector' },
        { name: 'Anti-Personnel Squad', power: 340, type: 'human', description: 'Kenny\'s special forces' },
        { name: 'Survey Corps Veteran', power: 310, type: 'human', description: 'Battle-hardened explorer' },
        { name: 'Military Police Captain', power: 330, type: 'human', description: 'Interior police commander' },
        { name: 'Garrison Commander', power: 325, type: 'human', description: 'Wall defense leader' },
        { name: 'Marley General', power: 370, type: 'human', description: 'High military command' },
        { name: 'Yeagerist Officer', power: 315, type: 'human', description: 'Eren faction commander' },
        { name: 'Eldian Spy Master', power: 290, type: 'human', description: 'Intelligence network head' },
        { name: 'Underground Crime Boss', power: 345, type: 'human', description: 'Criminal empire ruler' },
        { name: 'Titan Cult High Priest', power: 275, type: 'human', description: 'Religious fanatic leader' },
        { name: 'Marley Scientist', power: 260, type: 'human', description: 'Titan research specialist' },
        { name: 'Enhanced Soldier', power: 335, type: 'human', description: 'Experimentally modified fighter' },
        { name: 'Titan Summoner', power: 285, type: 'human', description: 'Can attract titans' },
        { name: 'Memory Manipulator', power: 300, type: 'human', description: 'Limited coordinate user' },
        { name: 'Paths Sensitive', power: 320, type: 'human', description: 'Can sense paths dimension' },
        { name: 'Serum Creator', power: 270, type: 'human', description: 'Titan transformation expert' },
        { name: 'Wall Engineer Master', power: 280, type: 'human', description: 'Fortification specialist' },
        { name: 'ODM Gear Master', power: 355, type: 'human', description: 'Mobility equipment expert' },
        { name: 'Thunder Spear Specialist', power: 340, type: 'human', description: 'Explosive weapon master' },
        { name: 'Blade Master', power: 360, type: 'human', description: 'Sword fighting expert' },
        { name: 'Tactical Commander', power: 315, type: 'human', description: 'Battle strategy specialist' },
        { name: 'Infiltration Expert', power: 295, type: 'human', description: 'Stealth operation master' },
        { name: 'Interrogation Specialist', power: 285, type: 'human', description: 'Information extraction expert' },
        { name: 'Propaganda Master', power: 265, type: 'human', description: 'Information warfare specialist' },
        { name: 'Supply Chain Director', power: 255, type: 'human', description: 'Logistics operation head' },
        { name: 'Intelligence Director', power: 325, type: 'human', description: 'Spy network commander' },
        { name: 'Special Operations', power: 365, type: 'human', description: 'Elite mission specialist' },
        { name: 'Counter-Intelligence', power: 305, type: 'human', description: 'Spy hunting expert' },
        { name: 'Psychological Warfare', power: 275, type: 'human', description: 'Mental manipulation specialist' },
        { name: 'Demolition Expert', power: 345, type: 'human', description: 'Explosive destruction master' },
        { name: 'Fortress Commander', power: 335, type: 'human', description: 'Defensive specialist' },
        { name: 'Mobile Unit Leader', power: 350, type: 'human', description: 'Rapid response commander' },
        { name: 'Siege Specialist', power: 330, type: 'human', description: 'Fortress assault expert' },
        { name: 'Urban Warfare Expert', power: 320, type: 'human', description: 'City combat specialist' },
        { name: 'Wilderness Tracker', power: 290, type: 'human', description: 'Outdoor hunting expert' },
        { name: 'Marley Admiral', power: 375, type: 'human', description: 'Naval command authority' },
        { name: 'Airship Captain', power: 310, type: 'human', description: 'Aerial warfare commander' },
        { name: 'Artillery Commander', power: 325, type: 'human', description: 'Heavy weapons specialist' },
        { name: 'Cavalry General', power: 340, type: 'human', description: 'Mounted warfare expert' },
        { name: 'Engineering Corps', power: 295, type: 'human', description: 'Military construction specialist' },
        { name: 'Medical Corps Director', power: 270, type: 'human', description: 'Battlefield medicine expert' },
        { name: 'Communications Chief', power: 280, type: 'human', description: 'Signal warfare specialist' },
        { name: 'Training Instructor', power: 315, type: 'human', description: 'Elite combat trainer' },
        { name: 'Weapon Research Director', power: 305, type: 'human', description: 'Military technology expert' },
        { name: 'Strategic Planning Head', power: 335, type: 'human', description: 'Long-term warfare specialist' },
        { name: 'Black Operations', power: 355, type: 'human', description: 'Classified mission expert' },
        { name: 'Counter-Titan Unit', power: 365, type: 'human', description: 'Anti-titan specialist' },
        { name: 'Elite Bodyguard', power: 340, type: 'human', description: 'VIP protection specialist' },
        { name: 'Assassination Squad', power: 350, type: 'human', description: 'Elite elimination unit' },
        { name: 'Reconnaissance Master', power: 300, type: 'human', description: 'Information gathering expert' },
        { name: 'Survival Instructor', power: 285, type: 'human', description: 'Harsh environment specialist' },
        { name: 'Combat Medic Elite', power: 310, type: 'human', description: 'Battlefield healing expert' },
        { name: 'Quartermaster General', power: 295, type: 'human', description: 'Military supply expert' },
        { name: 'Drill Sergeant Major', power: 320, type: 'human', description: 'Elite training specialist' },
        { name: 'Military Judge Advocate', power: 275, type: 'human', description: 'Military law expert' },
        { name: 'Chaplain Major', power: 260, type: 'human', description: 'Military spiritual leader' },
        { name: 'Historian Militant', power: 265, type: 'human', description: 'Military history expert' },
        { name: 'Cryptographer Master', power: 290, type: 'human', description: 'Code warfare specialist' },
        { name: 'Weather Specialist', power: 255, type: 'human', description: 'Environmental warfare expert' }
    ]
};

/**
 * Generate comprehensive combat encounters for all ranks
 */
function generateMegaCombatSystem() {
    logger.info('=== MASSIVE COMBAT SYSTEM EXPANSION ===');
    logger.info(`Normal Rank: ${massiveCombatExpansion.normal.length} enemies`);
    logger.info(`Rare Rank: ${massiveCombatExpansion.rare.length} enemies`);
    
    // Epic Rank Enemies (100+ enemies, CP: 800-1200)
    massiveCombatExpansion.epic = [
        // Nine Titans and Elite Shifters (30 variants)
        { name: 'Attack Titan Fragment', power: 950, type: 'titan', description: 'Piece of Attack Titan power' },
        { name: 'Colossal Titan Fragment', power: 1100, type: 'titan', description: 'Piece of Colossal Titan power' },
        { name: 'Armored Titan Fragment', power: 1050, type: 'titan', description: 'Piece of Armored Titan power' },
        { name: 'Female Titan Fragment', power: 900, type: 'titan', description: 'Piece of Female Titan power' },
        { name: 'Beast Titan Fragment', power: 1000, type: 'titan', description: 'Piece of Beast Titan power' },
        { name: 'Jaw Titan Fragment', power: 850, type: 'titan', description: 'Piece of Jaw Titan power' },
        { name: 'Cart Titan Fragment', power: 800, type: 'titan', description: 'Piece of Cart Titan power' },
        { name: 'Warhammer Titan Fragment', power: 1150, type: 'titan', description: 'Piece of Warhammer Titan power' },
        { name: 'Founding Titan Echo', power: 1200, type: 'titan', description: 'Echo of Founding Titan power' },
        { name: 'Titan Shifter Elite', power: 980, type: 'titan', description: 'Master of titan transformation' },
        { name: 'Warrior Candidate Alpha', power: 920, type: 'human', description: 'Top-tier Marley candidate' },
        { name: 'Nine Titans Hybrid', power: 1080, type: 'titan', description: 'Multiple titan power fusion' },
        { name: 'Paths Touched Shifter', power: 1040, type: 'titan', description: 'Paths dimension influenced' },
        { name: 'Royal Blood Shifter', power: 1120, type: 'titan', description: 'Royal bloodline titan' },
        { name: 'Coordinate Fragment', power: 1180, type: 'titan', description: 'Piece of coordinate power' },
        { name: 'Memory Inherited Titan', power: 960, type: 'titan', description: 'Previous holder memories' },
        { name: 'Wall Titan Commander', power: 1070, type: 'titan', description: 'Controls wall titans' },
        { name: 'Titan Serum Master', power: 890, type: 'human', description: 'Creates titan transformations' },
        { name: 'Eldian Heritage Warrior', power: 940, type: 'human', description: 'Awakened Eldian power' },
        { name: 'Marley Technology Elite', power: 870, type: 'human', description: 'Advanced military tech' },
        { name: 'Anti-Titan Specialist', power: 910, type: 'human', description: 'Titan hunting expert' },
        { name: 'Coordinate Sensitive', power: 1000, type: 'human', description: 'Can sense coordinate' },
        { name: 'Paths Navigator', power: 1030, type: 'human', description: 'Paths dimension traveler' },
        { name: 'Memory Manipulator', power: 950, type: 'human', description: 'Limited memory control' },
        { name: 'Titan Fusion Experiment', power: 1090, type: 'titan', description: 'Multiple powers combined' },
        { name: 'Hardening Master Titan', power: 1020, type: 'titan', description: 'Perfect hardening control' },
        { name: 'Steam Master Titan', power: 990, type: 'titan', description: 'Advanced steam abilities' },
        { name: 'Crystallization Titan', power: 1060, type: 'titan', description: 'Crystal formation expert' },
        { name: 'Bone Manipulation Titan', power: 1010, type: 'titan', description: 'Skeletal control master' },
        { name: 'Size Control Titan', power: 1140, type: 'titan', description: 'Variable size titan' }
    ];

    // Add 70 more Epic enemies...
    const epicExtended = [
        { name: 'Marley Military Command', power: 880, type: 'human', description: 'High command authority' },
        { name: 'Survey Corps Legend', power: 920, type: 'human', description: 'Legendary explorer' },
        { name: 'Wall Construction Master', power: 860, type: 'human', description: 'Fortress building expert' },
        { name: 'Titan Research Director', power: 840, type: 'human', description: 'Scientific research head' },
        { name: 'Underground Empire Lord', power: 900, type: 'human', description: 'Criminal empire ruler' },
        { name: 'Cult Supreme Leader', power: 820, type: 'human', description: 'Religious fanatic chief' },
        { name: 'Propaganda War Minister', power: 850, type: 'human', description: 'Information warfare head' },
        { name: 'Elite Bodyguard Captain', power: 930, type: 'human', description: 'VIP protection master' },
        { name: 'Black Operations Director', power: 970, type: 'human', description: 'Classified mission head' },
        { name: 'Counter-Intelligence Chief', power: 890, type: 'human', description: 'Spy hunting director' },
        { name: 'Special Forces Commander', power: 960, type: 'human', description: 'Elite unit leader' },
        { name: 'Tactical Operations Head', power: 910, type: 'human', description: 'Strategy specialist' },
        { name: 'Weapon Development Chief', power: 830, type: 'human', description: 'Military tech director' },
        { name: 'Medical Corps General', power: 810, type: 'human', description: 'Battlefield medicine head' },
        { name: 'Engineering Corps Chief', power: 870, type: 'human', description: 'Military construction head' },
        { name: 'Artillery Division Head', power: 940, type: 'human', description: 'Heavy weapons commander' },
        { name: 'Cavalry Division General', power: 920, type: 'human', description: 'Mounted warfare expert' },
        { name: 'Naval Operations Admiral', power: 950, type: 'human', description: 'Sea warfare commander' },
        { name: 'Airship Fleet Commander', power: 980, type: 'human', description: 'Aerial warfare head' },
        { name: 'Logistics Supreme Director', power: 800, type: 'human', description: 'Supply chain master' }
    ];
    
    massiveCombatExpansion.epic = massiveCombatExpansion.epic.concat(epicExtended);

    // Legendary Rank Enemies (100+ enemies, CP: 2000-3000)
    massiveCombatExpansion.legendary = [
        { name: 'Attack Titan Mastery', power: 2400, type: 'titan', description: 'Complete Attack Titan control' },
        { name: 'Founding Titan Fragment', power: 2800, type: 'titan', description: 'Partial Founding power' },
        { name: 'Coordinate Echo Master', power: 2600, type: 'titan', description: 'Coordinate power echo' },
        { name: 'Paths Dimension Walker', power: 2500, type: 'human', description: 'Travels paths freely' },
        { name: 'Memory God Fragment', power: 2300, type: 'human', description: 'Memory manipulation master' },
        { name: 'Royal Blood Awakened', power: 2700, type: 'human', description: 'Full royal bloodline' },
        { name: 'Ackerman Clan Chief', power: 2900, type: 'human', description: 'Ackerman bloodline master' },
        { name: 'Nine Titans Fusion', power: 2950, type: 'titan', description: 'Multiple titan fusion' },
        { name: 'Wall Titan Commander', power: 2650, type: 'titan', description: 'Commands wall titans' },
        { name: 'Titan War General', power: 2400, type: 'human', description: 'Great Titan War veteran' },
        { name: 'Eldian King Authority', power: 2750, type: 'human', description: 'Ancient royal power' },
        { name: 'Marley Empire Supreme', power: 2350, type: 'human', description: 'Marley ultimate authority' },
        { name: 'Coordinate Resonance', power: 2550, type: 'titan', description: 'Coordinate power resonance' },
        { name: 'Titan Evolution Master', power: 2450, type: 'titan', description: 'Evolved titan abilities' },
        { name: 'Paths Tree Guardian', power: 2600, type: 'titan', description: 'Protects paths tree' },
        { name: 'Memory Palace Lord', power: 2300, type: 'human', description: 'Memory storage master' },
        { name: 'Titan Serum God', power: 2200, type: 'human', description: 'Ultimate serum creator' },
        { name: 'Wall Secrets Keeper', power: 2500, type: 'human', description: 'Wall construction secrets' },
        { name: 'Ancient Technology', power: 2400, type: 'human', description: 'Lost tech knowledge' },
        { name: 'Titan Whisperer', power: 2350, type: 'human', description: 'Communicates with titans' }
    ];

    // Mythic Rank Enemies (100+ enemies, CP: 5000-6000)
    massiveCombatExpansion.mythic = [
        { name: 'Founding Titan Prime', power: 5500, type: 'titan', description: 'True Founding Titan power' },
        { name: 'Ymir Fritz Echo', power: 5800, type: 'titan', description: 'Original titan power echo' },
        { name: 'Paths Dimension Lord', power: 5400, type: 'titan', description: 'Rules paths dimension' },
        { name: 'Coordinate Supreme', power: 5900, type: 'titan', description: 'Ultimate coordinate power' },
        { name: 'Nine Titans Unity', power: 6000, type: 'titan', description: 'All nine titans unified' },
        { name: 'Memory Omniscience', power: 5300, type: 'human', description: 'All-knowing memory access' },
        { name: 'Rumbling Controller', power: 5700, type: 'human', description: 'Controls rumbling power' },
        { name: 'Titan Origin Source', power: 5600, type: 'titan', description: 'Original titan source' },
        { name: 'Eldian Progenitor', power: 5200, type: 'human', description: 'Original Eldian ancestor' },
        { name: 'Royal Blood Divine', power: 5800, type: 'human', description: 'Divine royal bloodline' },
        { name: 'Ackerman Godlike', power: 5900, type: 'human', description: 'Godlike Ackerman power' },
        { name: 'Titan Genesis Master', power: 5500, type: 'titan', description: 'Creates new titan types' },
        { name: 'Coordinate Transcendent', power: 5750, type: 'titan', description: 'Transcendent coordinate' },
        { name: 'Memory Weaver God', power: 5400, type: 'human', description: 'Weaves reality memories' },
        { name: 'Paths Tree Master', power: 5650, type: 'titan', description: 'Masters paths tree' },
        { name: 'Universal Coordinate', power: 5850, type: 'titan', description: 'Universal coordinate power' },
        { name: 'Titan Sovereign', power: 5700, type: 'titan', description: 'Supreme titan ruler' },
        { name: 'Reality Alterer', power: 5600, type: 'human', description: 'Alters reality itself' },
        { name: 'Time Memory Master', power: 5450, type: 'human', description: 'Controls time memories' },
        { name: 'Existence Controller', power: 5950, type: 'titan', description: 'Controls existence itself' }
    ];

    // Divine Rank Enemies (100+ enemies, CP: 9000-12000)
    massiveCombatExpansion.divine = [
        { name: 'Creator Titan God', power: 10500, type: 'titan', description: 'Divine titan creator' },
        { name: 'Reality Coordinate Divine', power: 11200, type: 'titan', description: 'Divine reality control' },
        { name: 'Dimensional Founder God', power: 10800, type: 'titan', description: 'Divine dimensional founder' },
        { name: 'Titan God Authority', power: 12000, type: 'titan', description: 'Divine titan authority' },
        { name: 'Paths Tree Divine', power: 11500, type: 'titan', description: 'Divine paths tree master' },
        { name: 'Memory Sovereign Divine', power: 9800, type: 'human', description: 'Divine memory sovereign' },
        { name: 'Time Manipulation God', power: 11800, type: 'human', description: 'Divine time controller' },
        { name: 'Universe Guardian Divine', power: 11000, type: 'titan', description: 'Divine universe protector' },
        { name: 'Divine Founding Titan', power: 12500, type: 'titan', description: 'Divine founding power' },
        { name: 'Celestial Coordinate', power: 11400, type: 'titan', description: 'Celestial coordinate power' },
        { name: 'Paths Divinity', power: 10900, type: 'titan', description: 'Divine paths control' },
        { name: 'Titan Creator Deity', power: 11700, type: 'titan', description: 'Deity of titan creation' },
        { name: 'Memory Divinity', power: 10200, type: 'human', description: 'Divine memory power' },
        { name: 'Rumbling Divinity', power: 11600, type: 'titan', description: 'Divine rumbling control' },
        { name: 'Divine Authority Supreme', power: 12200, type: 'titan', description: 'Supreme divine authority' },
        { name: 'Celestial Paths Master', power: 10700, type: 'titan', description: 'Celestial paths control' },
        { name: 'Divine Transcendence', power: 11300, type: 'titan', description: 'Divine transcendent power' },
        { name: 'God Emperor Titan', power: 12800, type: 'titan', description: 'God emperor of titans' },
        { name: 'Divine Memory God', power: 10600, type: 'human', description: 'Divine memory deity' },
        { name: 'Celestial Founding', power: 11900, type: 'titan', description: 'Celestial founding power' }
    ];

    // Cosmic Rank Enemies (100+ enemies, CP: 18000-25000)
    massiveCombatExpansion.cosmic = [
        { name: 'Universe Coordinate God', power: 20000, type: 'titan', description: 'Universal coordinate deity' },
        { name: 'Omniversal Founder', power: 22000, type: 'titan', description: 'Founder across all realities' },
        { name: 'Titan Multiverse Lord', power: 24000, type: 'titan', description: 'Lord of titan multiverse' },
        { name: 'Reality Shaper Divine', power: 21000, type: 'titan', description: 'Divine reality shaper' },
        { name: 'Existence Controller God', power: 23000, type: 'titan', description: 'God of existence control' },
        { name: 'Infinite Paths Master', power: 19000, type: 'titan', description: 'Master of infinite paths' },
        { name: 'Omnipotent Titan God', power: 25000, type: 'titan', description: 'Omnipotent titan deity' },
        { name: 'Cosmic Balance Keeper', power: 20500, type: 'titan', description: 'Cosmic balance guardian' },
        { name: 'Universal Destroyer', power: 23500, type: 'titan', description: 'Universal destruction force' },
        { name: 'Cosmic Creator God', power: 24500, type: 'titan', description: 'Cosmic creation deity' },
        { name: 'Infinite Coordinate', power: 21500, type: 'titan', description: 'Infinite coordinate power' },
        { name: 'Omniversal Memory', power: 19500, type: 'titan', description: 'Omniversal memory access' },
        { name: 'Cosmic Titan Emperor', power: 26000, type: 'titan', description: 'Emperor of cosmic titans' },
        { name: 'Reality Weaver God', power: 22500, type: 'titan', description: 'Divine reality weaver' },
        { name: 'Dimensional Lord God', power: 23800, type: 'titan', description: 'God of all dimensions' },
        { name: 'Cosmic Founding God', power: 24800, type: 'titan', description: 'Cosmic founding deity' },
        { name: 'Universal Memory God', power: 20200, type: 'titan', description: 'Universal memory deity' },
        { name: 'Infinite Titan God', power: 27000, type: 'titan', description: 'Infinite titan deity' },
        { name: 'Cosmic Paths God', power: 19800, type: 'titan', description: 'Cosmic paths deity' },
        { name: 'Omniversal Ruler', power: 25500, type: 'titan', description: 'Ruler of all realities' }
    ];

    // Transcendent Rank Enemies (100+ enemies, CP: 35000-50000)
    massiveCombatExpansion.transcendent = [
        { name: 'Beyond Reality Entity', power: 40000, type: 'titan', description: 'Entity beyond reality' },
        { name: 'Conceptual Titan God', power: 42000, type: 'titan', description: 'Titan as pure concept' },
        { name: 'Meta-Coordinate Entity', power: 45000, type: 'titan', description: 'Coordinate beyond coordinates' },
        { name: 'Transcendent Founder', power: 47000, type: 'titan', description: 'Founder beyond existence' },
        { name: 'Abstract Paths Entity', power: 38000, type: 'titan', description: 'Abstract paths being' },
        { name: 'Meta-Reality Controller', power: 44000, type: 'titan', description: 'Controls reality concept' },
        { name: 'Transcendent Memory', power: 36000, type: 'titan', description: 'Memory beyond spacetime' },
        { name: 'Conceptual Authority', power: 46000, type: 'titan', description: 'Authority over concepts' },
        { name: 'Meta-Existence Entity', power: 48000, type: 'titan', description: 'Existence beyond existence' },
        { name: 'Transcendent Creator', power: 41000, type: 'titan', description: 'Creator beyond creation' },
        { name: 'Abstract Titan Emperor', power: 49000, type: 'titan', description: 'Abstract titan emperor' },
        { name: 'Meta-Omnipotence', power: 50000, type: 'titan', description: 'Omnipotence over omnipotence' },
        { name: 'Transcendent Paths God', power: 43000, type: 'titan', description: 'Transcendent paths deity' },
        { name: 'Conceptual Founding', power: 46500, type: 'titan', description: 'Founding as concept' },
        { name: 'Meta-Coordinate God', power: 48500, type: 'titan', description: 'God of coordinate concepts' },
        { name: 'Transcendent Reality', power: 47500, type: 'titan', description: 'Reality beyond reality' },
        { name: 'Abstract Memory God', power: 39000, type: 'titan', description: 'Memory as abstract force' },
        { name: 'Meta-Creation Entity', power: 44500, type: 'titan', description: 'Creation beyond creation' },
        { name: 'Transcendent Authority', power: 48200, type: 'titan', description: 'Authority transcending power' },
        { name: 'Conceptual Universe', power: 45500, type: 'titan', description: 'Universe as concept' }
    ];

    // Omnipotent Rank Enemies (50+ enemies, CP: 75000-100000)
    massiveCombatExpansion.omnipotent = [
        { name: 'Pure Omnipotent Entity', power: 85000, type: 'titan', description: 'True omnipotence incarnate' },
        { name: 'Absolute Authority God', power: 90000, type: 'titan', description: 'Unchallengeable authority' },
        { name: 'Omnipotent Titan Emperor', power: 95000, type: 'titan', description: 'Omnipotent titan ruler' },
        { name: 'Ultimate Coordinate God', power: 88000, type: 'titan', description: 'Limitless coordinate' },
        { name: 'Omnipotent Founding', power: 92000, type: 'titan', description: 'Boundless founding power' },
        { name: 'Infinite Power Entity', power: 100000, type: 'titan', description: 'Truly limitless power' },
        { name: 'Omnipotent Creator God', power: 96000, type: 'titan', description: 'Unlimited creation power' },
        { name: 'Absolute Reality God', power: 93000, type: 'titan', description: 'Unrestricted reality control' },
        { name: 'Omnipotent Memory', power: 86000, type: 'titan', description: 'Boundless memory power' },
        { name: 'Ultimate Existence', power: 98000, type: 'titan', description: 'Existence beyond concepts' },
        { name: 'Omnipotent Paths God', power: 89000, type: 'titan', description: 'Infinite paths reach' },
        { name: 'Absolute Control Entity', power: 97000, type: 'titan', description: 'Control over everything' },
        { name: 'Omnipotent Supreme', power: 99000, type: 'titan', description: 'Supreme omnipotent authority' },
        { name: 'Infinite Authority God', power: 94000, type: 'titan', description: 'Boundaryless authority' },
        { name: 'Omnipotent Deity', power: 91000, type: 'titan', description: 'True omnipotent god' },
        { name: 'Ultimate Power God', power: 95500, type: 'titan', description: 'Power surpassing all' },
        { name: 'Omnipotent Mastery', power: 87000, type: 'titan', description: 'Mastery over existence' },
        { name: 'Absolute Omnipotence', power: 99500, type: 'titan', description: 'Purest omnipotence' },
        { name: 'Omnipotent Eternal', power: 93500, type: 'titan', description: 'Eternal omnipotent power' },
        { name: 'Ultimate Omnipotent', power: 100000, type: 'titan', description: 'Ultimate omnipotent force' }
    ];

    // Absolute Rank Enemies (50 enemies, CP: 500000-1000000)
    massiveCombatExpansion.absolute = [
        { name: 'The One Above All Titans', power: 750000, type: 'titan', description: 'Supreme titan entity above all' },
        { name: 'Source of All Existence', power: 900000, type: 'titan', description: 'Original source of reality' },
        { name: 'The Absolute Titan', power: 1000000, type: 'titan', description: 'Beyond description or comprehension' },
        { name: 'Prime Mover Titan', power: 600000, type: 'titan', description: 'First cause of all motion' },
        { name: 'Eternal Infinite', power: 800000, type: 'titan', description: 'Eternal infinite being' },
        { name: 'Ultimate Reality', power: 950000, type: 'titan', description: 'Ultimate reality itself' },
        { name: 'Absolute Authority', power: 700000, type: 'titan', description: 'Authority without limit' },
        { name: 'Perfect Being', power: 850000, type: 'titan', description: 'Perfect in all aspects' },
        { name: 'Supreme Existence', power: 920000, type: 'titan', description: 'Supreme form of existence' },
        { name: 'The Absolute Creator', power: 880000, type: 'titan', description: 'Creator of all creation' },
        { name: 'Ultimate Foundation', power: 750000, type: 'titan', description: 'Foundation of reality' },
        { name: 'Supreme Power', power: 940000, type: 'titan', description: 'Supreme power incarnate' },
        { name: 'Absolute Unity', power: 820000, type: 'titan', description: 'Unity of all existence' },
        { name: 'Perfect Order', power: 780000, type: 'titan', description: 'Perfect cosmic order' },
        { name: 'Ultimate Truth', power: 860000, type: 'titan', description: 'Ultimate truth itself' },
        { name: 'Absolute Perfection', power: 910000, type: 'titan', description: 'Perfection beyond measure' },
        { name: 'Supreme Unity', power: 830000, type: 'titan', description: 'Unity beyond division' },
        { name: 'Ultimate Authority', power: 970000, type: 'titan', description: 'Authority beyond question' },
        { name: 'Absolute Omnipotence', power: 990000, type: 'titan', description: 'True absolute omnipotence' },
        { name: 'The Final Entity', power: 1000000, type: 'titan', description: 'The final supreme entity' }
    ];

    return massiveCombatExpansion;
}

module.exports = {
    massiveCombatExpansion,
    generateMegaCombatSystem
};